<?php

declare(strict_types=1);

namespace Tsitsishvili\Documentator\TypeScript;

use Tsitsishvili\Documentator\OpenApi\OpenApiMethods;

/**
 * Generates a dependency-free TypeScript fetch client from Documentator's
 * OpenAPI output. The result targets browsers and modern Node.js runtimes.
 */
final class TypeScriptClientGenerator
{
    /** @var array<string, int> */
    private array $typeNames = [];

    /**
     * @param  array<string, mixed>  $spec
     */
    public function generate(array $spec, string $clientName = 'DocumentatorClient'): string
    {
        $this->typeNames = [];
        $clientName = $this->identifier($clientName, 'DocumentatorClient', true);
        $types = [];
        $methods = [];

        foreach ((array) ($spec['components']['schemas'] ?? []) as $name => $schema) {
            if (is_array($schema) || is_bool($schema)) {
                $typeName = $this->typeName((string) $name);
                $this->typeNames[$typeName] = 1;
                $types[] = $this->declaration($typeName, $schema);
            }
        }

        foreach ((array) ($spec['paths'] ?? []) as $path => $pathItem) {
            if (! is_string($path) || ! is_array($pathItem)) {
                continue;
            }

            foreach (OpenApiMethods::ALL as $method) {
                $operation = $pathItem[$method] ?? null;

                if (! is_array($operation)) {
                    continue;
                }

                [$operationTypes, $operationMethod] = $this->operation($path, $method, $pathItem, $operation);
                array_push($types, ...$operationTypes);
                $methods[] = $operationMethod;
            }
        }

        $baseUrl = (string) ($spec['servers'][0]['url'] ?? '');
        $source = [
            '/* eslint-disable */',
            '// Generated by tsitsishvili/documentator. Do not edit by hand.',
            '',
            'export interface DocumentatorClientOptions {',
            '  baseUrl?: string;',
            '  token?: string;',
            '  headers?: Record<string, string>;',
            '  credentials?: RequestCredentials;',
            '  fetch?: typeof globalThis.fetch;',
            '}',
            '',
            'export class DocumentatorApiError extends Error {',
            '  constructor(',
            '    public readonly status: number,',
            '    public readonly body: unknown,',
            '    message = `HTTP ${status}`,',
            '  ) {',
            '    super(message);',
            '    this.name = "DocumentatorApiError";',
            '  }',
            '}',
            '',
            ...$this->spaced($types),
            "export class {$clientName} {",
            '  private readonly baseUrl: string;',
            '  private readonly token?: string;',
            '  private readonly headers: Record<string, string>;',
            '  private readonly credentials: RequestCredentials;',
            '  private readonly fetcher: typeof globalThis.fetch;',
            '',
            '  constructor(options: DocumentatorClientOptions = {}) {',
            '    this.baseUrl = (options.baseUrl ?? '.$this->literal($baseUrl).').replace(/\/$/, "");',
            '    this.token = options.token;',
            '    this.headers = options.headers ?? {};',
            '    this.credentials = options.credentials ?? "same-origin";',
            '    this.fetcher = options.fetch ?? globalThis.fetch.bind(globalThis);',
            '  }',
            '',
            ...$this->indentMethods($methods),
            '  private buildUrl(path: string, query: URLSearchParams): string {',
            '    const suffix = query.toString();',
            '    return `${this.baseUrl}${path}${suffix ? `?${suffix}` : ""}`;',
            '  }',
            '',
            '  private appendQuery(query: URLSearchParams, name: string, value: unknown): void {',
            '    if (value === undefined || value === null) return;',
            '    if (Array.isArray(value)) {',
            '      value.forEach((item) => this.appendQuery(query, name, item));',
            '      return;',
            '    }',
            '    query.append(name, typeof value === "object" ? JSON.stringify(value) : String(value));',
            '  }',
            '',
            '  private encodeBody(value: unknown, mediaType: string, headers: Record<string, string>): BodyInit | undefined {',
            '    if (value === undefined) return undefined;',
            '    if (mediaType === "multipart/form-data") {',
            '      const form = new FormData();',
            '      Object.entries(value as Record<string, unknown>).forEach(([name, item]) => {',
            '        if (Array.isArray(item)) item.forEach((part) => form.append(name, part as string | Blob));',
            '        else if (item !== undefined && item !== null) form.append(name, item as string | Blob);',
            '      });',
            '      return form;',
            '    }',
            '    headers["Content-Type"] = mediaType;',
            '    if (mediaType === "application/x-www-form-urlencoded") {',
            '      const form = new URLSearchParams();',
            '      Object.entries(value as Record<string, unknown>).forEach(([name, item]) => this.appendQuery(form, name, item));',
            '      return form;',
            '    }',
            '    return mediaType === "application/json" || mediaType.endsWith("+json")',
            '      ? JSON.stringify(value)',
            '      : value as BodyInit;',
            '  }',
            '',
            '  private async request<T>(url: string, init: RequestInit, mode: "json" | "text" | "blob" | "stream" | "void"): Promise<T> {',
            '    const headers: Record<string, string> = { ...this.headers, ...(init.headers as Record<string, string> ?? {}) };',
            '    if (this.token && !headers.Authorization) headers.Authorization = `Bearer ${this.token}`;',
            '    const response = await this.fetcher(url, { ...init, headers, credentials: this.credentials });',
            '    if (!response.ok) {',
            '      const contentType = response.headers.get("Content-Type") ?? "";',
            '      const body = contentType.includes("json") ? await response.json() : await response.text();',
            '      throw new DocumentatorApiError(response.status, body, `HTTP ${response.status} ${response.statusText}`);',
            '    }',
            '    if (mode === "void") return undefined as T;',
            '    if (mode === "stream") {',
            '      if (!response.body) throw new Error("Streaming response did not provide a body");',
            '      return response.body as unknown as T;',
            '    }',
            '    if (mode === "blob") return await response.blob() as unknown as T;',
            '    if (mode === "text") return await response.text() as unknown as T;',
            '    return await response.json() as T;',
            '  }',
            '}',
            '',
        ];

        return implode(PHP_EOL, $source);
    }

    /**
     * @param  array<string, mixed>  $pathItem
     * @param  array<string, mixed>  $operation
     * @return array{0: array<int, string>, 1: string}
     */
    private function operation(string $path, string $method, array $pathItem, array $operation): array
    {
        $function = $this->identifier(
            (string) ($operation['operationId'] ?? $method.'_'.$path),
            'operation',
        );
        $baseName = $this->identifier($function, 'Operation', true);
        $requestName = $this->uniqueTypeName($baseName.'Request');
        $responseName = $this->uniqueTypeName($baseName.'Response');
        $parameters = array_merge(
            is_array($pathItem['parameters'] ?? null) ? $pathItem['parameters'] : [],
            is_array($operation['parameters'] ?? null) ? $operation['parameters'] : [],
        );
        $groups = ['path' => [], 'query' => [], 'header' => [], 'cookie' => []];

        foreach ($parameters as $parameter) {
            if (! is_array($parameter) || ! isset($groups[$parameter['in'] ?? ''])) {
                continue;
            }

            $groups[$parameter['in']][$parameter['name']] = $parameter;
        }

        [$bodySchema, $bodyMediaType, $bodyRequired] = $this->requestBody($operation);
        [$responseSchema, $responseMode, $streaming] = $this->successResponse($operation);
        $requestParts = [];

        foreach ($groups as $location => $items) {
            if ($items !== []) {
                $required = $location === 'path';
                $requestLocation = match ($location) {
                    'header' => 'headers',
                    'cookie' => 'cookies',
                    default => $location,
                };
                $requestParts[] = '  '.$requestLocation.($required ? '' : '?').': '.$this->parameterObject($items).';';
            }
        }

        if ($bodySchema !== null) {
            $requestParts[] = '  body'.($bodyRequired ? '' : '?').': '.$this->schemaType($bodySchema).';';
        }

        $types = [];

        if ($requestParts !== []) {
            $types[] = "export interface {$requestName} {".PHP_EOL.implode(PHP_EOL, $requestParts).PHP_EOL.'}';
        }

        $responseType = 'void';

        if ($responseSchema !== null) {
            if ($streaming) {
                $types[] = "export type {$responseName}Item = ".$this->schemaType($responseSchema).';';
                $types[] = "export type {$responseName} = ReadableStream<Uint8Array>;";
            } else {
                $types[] = "export type {$responseName} = ".$this->schemaType($responseSchema).';';
            }
            $responseType = $responseName;
        }

        $summary = trim((string) ($operation['summary'] ?? ''));
        $description = trim((string) ($operation['description'] ?? ''));
        $comments = array_values(array_filter([$summary, $description], fn (string $line): bool => $line !== ''));
        $lines = [];

        if ($comments !== []) {
            $lines[] = '/**';
            foreach ($comments as $comment) {
                $lines[] = ' * '.str_replace('*/', '*\/', $comment);
            }
            $lines[] = ' */';
        }

        $argument = $requestParts === [] ? '' : "request: {$requestName}";
        $lines[] = "async {$function}({$argument}): Promise<{$responseType}> {";
        $pathExpression = preg_replace_callback(
            '/\{([^}]+)\}/',
            fn (array $matches): string => '${encodeURIComponent(String(request.path['.$this->literal($matches[1]).']))}',
            $path,
        ) ?? $path;
        $lines[] = '  const path = `'.$pathExpression.'`;';
        $lines[] = '  const query = new URLSearchParams();';

        foreach ($groups['query'] as $name => $parameter) {
            $lines[] = '  this.appendQuery(query, '.$this->literal((string) $name).', request.query?.['.$this->literal((string) $name).']);';
        }

        $lines[] = '  const headers: Record<string, string> = {};';

        foreach (array_keys($groups['header']) as $name) {
            $access = 'request.headers?.['.$this->literal((string) $name).']';
            $lines[] = "  if ({$access} !== undefined) headers[".$this->literal((string) $name)."] = String({$access});";
        }

        if ($groups['cookie'] !== []) {
            $cookieParts = [];
            foreach (array_keys($groups['cookie']) as $name) {
                $cookieParts[] = '['.$this->literal((string) $name).', request.cookies?.['.$this->literal((string) $name).']]';
            }
            $lines[] = '  // Browsers use their cookie jar; the Cookie header is effective in server-side fetch runtimes.';
            $lines[] = '  const cookies = ['.implode(', ', $cookieParts).']';
            $lines[] = '    .filter((entry) => entry[1] !== undefined)';
            $lines[] = '    .map((entry) => `${entry[0]}=${encodeURIComponent(String(entry[1]))}`);';
            $lines[] = '  if (cookies.length) headers.Cookie = cookies.join("; ");';
        }

        if ($bodySchema !== null) {
            $lines[] = '  const body = this.encodeBody(request.body, '.$this->literal($bodyMediaType).', headers);';
        }

        $lines[] = '  return this.request<'.$responseType.'>(';
        $lines[] = '    this.buildUrl(path, query),';
        $lines[] = '    { method: '.$this->literal(strtoupper($method)).', headers'.($bodySchema !== null ? ', body' : '').' },';
        $lines[] = '    '.$this->literal($responseMode).',';
        $lines[] = '  );';
        $lines[] = '}';

        return [$types, implode(PHP_EOL, $lines)];
    }

    /**
     * @param  array<string, mixed>  $operation
     * @return array{0: array<string, mixed>|bool|null, 1: string, 2: bool}
     */
    private function requestBody(array $operation): array
    {
        $requestBody = is_array($operation['requestBody'] ?? null) ? $operation['requestBody'] : [];

        foreach ((array) ($requestBody['content'] ?? []) as $mediaType => $media) {
            if (is_array($media) && (is_array($media['schema'] ?? null) || is_bool($media['schema'] ?? null))) {
                return [$media['schema'], (string) $mediaType, (bool) ($requestBody['required'] ?? false)];
            }
        }

        return [null, 'application/json', false];
    }

    /**
     * @param  array<string, mixed>  $operation
     * @return array{0: array<string, mixed>|bool|null, 1: string, 2: bool}
     */
    private function successResponse(array $operation): array
    {
        foreach ((array) ($operation['responses'] ?? []) as $status => $response) {
            if (! preg_match('/^2(?:\d\d|XX)$/i', (string) $status) || ! is_array($response)) {
                continue;
            }

            foreach ((array) ($response['content'] ?? []) as $mediaType => $media) {
                if (! is_array($media)) {
                    continue;
                }

                $streaming = array_key_exists('itemSchema', $media);
                $schema = $streaming ? $media['itemSchema'] : ($media['schema'] ?? null);

                if (! is_array($schema) && ! is_bool($schema)) {
                    continue;
                }

                $mediaType = strtolower((string) $mediaType);
                $mode = $streaming
                    ? 'stream'
                    : ($mediaType === 'application/json' || str_ends_with($mediaType, '+json') ? 'json' : 'text');

                if (($schema['format'] ?? null) === 'binary' || ($schema['contentEncoding'] ?? null) === 'base64') {
                    $mode = 'blob';
                }

                return [$schema, $mode, $streaming];
            }

            return [null, 'void', false];
        }

        return [null, 'void', false];
    }

    /**
     * @param  array<string, array<string, mixed>>  $parameters
     */
    private function parameterObject(array $parameters): string
    {
        $properties = [];

        foreach ($parameters as $name => $parameter) {
            $properties[] = $this->property((string) $name).
                (($parameter['required'] ?? false) ? '' : '?').': '.
                $this->schemaType($parameter['schema'] ?? true).';';
        }

        return '{ '.implode(' ', $properties).' }';
    }

    private function declaration(string $name, array|bool $schema): string
    {
        if (is_array($schema)
            && ($schema['type'] ?? null) === 'object'
            && ! isset($schema['oneOf'], $schema['anyOf'], $schema['allOf'], $schema['$ref'])) {
            return "export interface {$name} ".$this->objectType($schema);
        }

        return "export type {$name} = ".$this->schemaType($schema).';';
    }

    private function schemaType(mixed $schema): string
    {
        if ($schema === false) {
            return 'never';
        }

        if ($schema === true || ! is_array($schema)) {
            return 'unknown';
        }

        if (isset($schema['$ref'])) {
            return $this->typeName((string) basename(str_replace('\\', '/', (string) $schema['$ref'])));
        }

        if (is_array($schema['enum'] ?? null) && $schema['enum'] !== []) {
            return implode(' | ', array_map(fn (mixed $value): string => $this->literal($value), $schema['enum']));
        }

        foreach (['oneOf', 'anyOf'] as $composite) {
            if (is_array($schema[$composite] ?? null) && $schema[$composite] !== []) {
                return implode(' | ', array_map(fn (mixed $branch): string => $this->schemaType($branch), $schema[$composite]));
            }
        }

        if (is_array($schema['allOf'] ?? null) && $schema['allOf'] !== []) {
            return implode(' & ', array_map(fn (mixed $branch): string => $this->schemaType($branch), $schema['allOf']));
        }

        $types = is_array($schema['type'] ?? null) ? $schema['type'] : [$schema['type'] ?? null];
        $mapped = [];

        foreach ($types as $type) {
            $mapped[] = match ($type) {
                'null' => 'null',
                'boolean' => 'boolean',
                'integer', 'number' => 'number',
                'string' => 'string',
                'array' => 'Array<'.$this->schemaType($schema['items'] ?? true).'>',
                'object' => $this->objectType($schema),
                default => isset($schema['properties']) ? $this->objectType($schema) : 'unknown',
            };
        }

        return implode(' | ', array_values(array_unique($mapped)));
    }

    /**
     * @param  array<string, mixed>  $schema
     */
    private function objectType(array $schema): string
    {
        $required = array_map('strval', (array) ($schema['required'] ?? []));
        $properties = [];

        foreach ((array) ($schema['properties'] ?? []) as $name => $property) {
            $properties[] = $this->property((string) $name).
                (in_array((string) $name, $required, true) ? '' : '?').': '.
                $this->schemaType($property).';';
        }

        if (is_array($schema['additionalProperties'] ?? null) || ($schema['additionalProperties'] ?? null) === true) {
            $additional = $schema['additionalProperties'] === true ? 'unknown' : $this->schemaType($schema['additionalProperties']);
            $properties[] = "[key: string]: {$additional};";
        }

        return '{ '.implode(' ', $properties).' }';
    }

    private function property(string $name): string
    {
        return preg_match('/^[A-Za-z_$][A-Za-z0-9_$]*$/', $name) === 1 ? $name : $this->literal($name);
    }

    private function typeName(string $name): string
    {
        return $this->identifier($name, 'Schema', true);
    }

    private function uniqueTypeName(string $name): string
    {
        $name = $this->typeName($name);
        $count = $this->typeNames[$name] ?? 0;
        $this->typeNames[$name] = $count + 1;

        return $count === 0 ? $name : $name.($count + 1);
    }

    private function identifier(string $value, string $fallback, bool $pascal = false): string
    {
        $parts = preg_split('/[^A-Za-z0-9_$]+/', $value, -1, PREG_SPLIT_NO_EMPTY) ?: [];
        $identifier = implode('', array_map(
            fn (string $part, int $index): string => ($pascal || $index > 0) ? ucfirst($part) : lcfirst($part),
            $parts,
            array_keys($parts),
        ));
        $identifier = $identifier !== '' ? $identifier : $fallback;

        if (preg_match('/^[A-Za-z_$]/', $identifier) !== 1) {
            $identifier = '_'.$identifier;
        }

        return $identifier;
    }

    private function literal(mixed $value): string
    {
        return (string) json_encode($value, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR);
    }

    /**
     * @param  array<int, string>  $blocks
     * @return array<int, string>
     */
    private function spaced(array $blocks): array
    {
        $lines = [];

        foreach ($blocks as $block) {
            array_push($lines, ...explode(PHP_EOL, $block));
            $lines[] = '';
        }

        return $lines;
    }

    /**
     * @param  array<int, string>  $methods
     * @return array<int, string>
     */
    private function indentMethods(array $methods): array
    {
        $lines = [];

        foreach ($methods as $method) {
            foreach (explode(PHP_EOL, $method) as $line) {
                $lines[] = '  '.$line;
            }
            $lines[] = '';
        }

        return $lines;
    }
}
